openapi: "3.0.0"

info:
  version: 1.0.0
  title: SDC Service API
  license:
    name: Apache License 2.0

servers:
  - url: http://localhost:8080/

paths:
  /valuation/value:
    post:
      summary: Request mapping for the value
      operationId: value
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ValueRequest"
      responses:
        '200':
          description: Value was calculated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValueResult"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /valuation/margin:
    post:
      summary: Request mapping for the margin
      operationId: margin
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MarginRequest"
      responses:
        '200':
          description: Margin was calculated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MarginResult"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /valuation/test/product:
    post:
      summary: Request mapping for the value of a product (using fixed market data)
      operationId: testProductValue
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - tradeData
              properties:
                tradeData:
                  type: string
                  format: binary
      responses:
        '200':
          description: Value was calculated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValueResult"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /info/git:
    get:
      summary: Request info on Git version and tags
      operationId: info-git
      responses:
        '200':
          description: Info returned
          content:
            application/json:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /info/finmath:
    get:
      summary: Request info on finmath-lib version and tags
      operationId: info-finmath
      responses:
        '200':
          description: Info returned
          content:
            application/json:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /editor/generate-xml:
    post:
      summary: Request mapping for generation of the trade data XML
      operationId: generate-xml
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SdcXmlRequest"
      responses:
        '200':
          description: XML was generated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SdcXmlResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /editor/evaluate-from-editor:
    post:
      summary: Request mapping for valuation of the trade data coming from the editor.
      operationId: evaluate-from-editor
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SdcXmlRequest"
      responses:
        '200':
          description: Valuation successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValueResult"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:
    ValueResult:
      $ref: "schemas/openapi-schemas/ValueResult.yml"
    MarginResult:
      $ref: "schemas/openapi-schemas/MarginResult.yml"
    Error:
      $ref: "schemas/openapi-schemas/Error.yml"
    SdcXmlResponse:
      $ref: "schemas/openapi-schemas/SdcXmlResponse.yml"
    ValueRequest:
      $ref: "schemas/openapi-schemas/ValueRequest.yml"
    MarginRequest:
      $ref: "schemas/openapi-schemas/MarginRequest.yml"
    SdcXmlRequest:
      $ref: "schemas/openapi-schemas/SdcXmlRequest.yml"